# Generated by Django 2.2.12 on 2022-09-17 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='mov_id',
            new_name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
