# Generated by Django 2.2.12 on 2022-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220917_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=0),
        ),
    ]
