# Generated by Django 2.2.12 on 2022-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20220918_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('director_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('movie_id', 'director_id')},
            },
        ),
    ]
