# Generated by Django 2.2.12 on 2022-09-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_actor',
            name='actor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Actor'),
        ),
        migrations.AlterField(
            model_name='movie_actor',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Director'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
